env:
  browser: true
  jasmine: true
  jquery: true
extends: 'eslint:recommended'
globals:
  Battletype: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
